### PR TITLE
Relicense to Creative Commons BY 4.0

### PR DESCRIPTION
**Pull request by dfsek**
Relicenses to a very permissive creative license. (This repository actually does not currently have a license, making it ARR in its current state).

I chose CC over a permissive *software* license such as the MIT License because this repository, imo, is more of a general creative work than a piece of software, and the license should reflect that.

### CODE REVIEW

**Comment by dfsek** [comment]
I give my explicit permission to relicense my contributions under the terms of the Creative Commons Attribution 4.0 International Public License.

**Comment by DeathShadez** [comment]
I give my explicit permission to relicense my contributions under the terms of the Creative Commons Attribution 4.0 International Public License.

**Comment by warben0** [comment]
I give my explicit permission to relicense my contributions under the terms of the Creative Commons Attribution 4.0 International Public License.

**Comment by Roan-V** [comment]
I give my explicit permission to relicense my contributions under the terms of the Creative Commons Attribution 4.0 International Public License.

**Comment by duplexsystem** [comment]
I give my explicit permission to relicense my contributions under the terms of the Creative Commons Attribution 4.0 International Public License.

**Review by solonovamax — APPROVED** [review]
I give my explicit permission to relicense all of my contributions under the terms of the Creative Commons Attribution 4.0 International (CC BY 4.0) Public License.

**Pull request merged**
